OENIK_PROG3_2020_2_DS1D6V/FelevesFeladat.MVC/Models/Band.cs
// <copyright file="Band.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace FelevesFeladat.MVC.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// The band class.
    /// </summary>
    public class Band
    {
        /// <summary>
        /// Gets or sets the band's id.
        /// </summary>
        [Display(Name = "Band id: ")]
        [Required]
        public int ID { get; set; }

        /// <summary>
        /// Gets or sets the name of the band.
        /// </summary>
        [Required]
        [Display(Name = "Band name: ")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the origin of the band.
        /// </summary>
        [Required]
        [Display(Name = "Band Origin: ")]
        public string Origin { get; set; }

        /// <summary>
        /// Gets or sets the members of the band.
        /// </summary>
        [Required]
        [Display(Name = "Band members: ")]
        public string Members { get; set; }

        /// <summary>
        /// Gets or sets the band's genre of music.
        /// </summary>
        [Required]
        [StringLength(130, MinimumLength = 2)]
        [Display(Name = "Band genres: ")]
        public string Genres { get; set; }

        /// <summary>
        /// Gets or sets the datetime when the band was formed.
        /// </summary>
        [Required]
        [Display(Name = "Band formed: ")]
        public DateTime Formed { get; set; }
    }
}

OENIK_PROG3_2020_2_DS1D6V/FelevesFeladat.MVC/Controllers/BandsController.cs
// <copyright file="BandsController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace FelevesFeladat.MVC.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using AutoMapper;
    using FelevesFeladat.Logic;
    using FelevesFeladat.MVC.Models;
    using Microsoft.AspNetCore.Mvc;

    /// <summary>
    /// The band controller class.
    /// </summary>
    public class BandsController : Controller
    {
        private IEditDataStackLogic editDataStackLogic;
        private IGetEntityByDefinitionLogic getEntityByDefinitionLogic;
        private IModifyEntityLogic modifyEntityLogic;
        private IMapper mapper;
        private BandListViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="BandsController"/> class.
        /// The constructor of the band controller class.
        /// </summary>
        /// <param name="editDataStackLogic">The editDataStackLogic.</param>
        /// <param name="getEntityByDefinitionLogic">The getEntityByDefinitionLogic.</param>
        /// <param name="modifyEntityLogic">The modifyEntityLogic.</param>
        /// <param name="mapper">The auto mapper.</param>
        public BandsController(IEditDataStackLogic editDataStackLogic, IGetEntityByDefinitionLogic getEntityByDefinitionLogic, IModifyEntityLogic modifyEntityLogic, IMapper mapper)
        {
            this.editDataStackLogic = editDataStackLogic;
            this.getEntityByDefinitionLogic = getEntityByDefinitionLogic;
            this.modifyEntityLogic = modifyEntityLogic;
            this.mapper = mapper;
            this.vm = new BandListViewModel();
            this.vm.EditedBand = new Models.Band();
            var bands = this.getEntityByDefinitionLogic.GetAllBands();
            this.vm.Bands = this.mapper.Map<IList<Data.Band>, List<Models.Band>>(bands);
        }

        /// <summary>
        /// The actionresult of the index view.
        /// </summary>
        /// <returns>The actionresult.</returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("BandsIndex", this.vm);
        }

        // Get: Bands/Details/5

        /// <summary>
        /// The actionresult of the details view.
        /// </summary>
        /// <param name="id">The id of the selected band.</param>
        /// <returns>The actionresult.</returns>
        public IActionResult Details(int id)
        {
            return this.View("BandsDetails", this.GetBandModel(id));
        }

        // GET: Bands/Remove/5

        /// <summary>
        /// The actionresult of the remove view.
        /// </summary>
        /// <param name="id">The id of the to be removed band.</param>
        /// <returns>The actionresult.</returns>
        public IActionResult Remove(int id)
        {
            this.TempData["editResult"] = "Delete OK";
            this.editDataStackLogic.RemoveBand(id.ToString(new CultureInfo("en")));
            return this.RedirectToAction(nameof(this.Index));
        }

        // GET: Bands/Edit/5

        /// <summary>
        /// The actionresult of the edit view.
        /// </summary>
        /// <param name="id">The id of the selected band for the edit.</param>
        /// <returns>The actionresult.</returns>
        public IActionResult Edit(int id)
        {
            this.ViewData["editAction"] = "Edit";
            this.vm.EditedBand = this.GetBandModel(id);
            return this.View("BandsIndex", this.vm);
        }

        // POST: Bands/Edit + 1car + editAction

        /// <summary>
        /// The actionresult of the edit view.
        /// </summary>
        /// <param name="band">The band model.</param>
        /// <param name="editAction">The action in a string.</param>
        /// <returns>The actionresult.</returns>
        [HttpPost]
        public IActionResult Edit(Models.Band band, string editAction)
        {
            if (this.ModelState.IsValid && band != null)
            {
                this.TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    try
                    {
                        this.editDataStackLogic.InsertBand(band.Name, band.Origin, band.Members, band.Genres, band.Formed.ToString(new CultureInfo("en")));
                    }
                    catch (ArgumentException ex)
                    {
                        this.TempData["editResult"] = "AddBand FAIL: " + ex.Message;
                    }
                }
                else
                {
                    this.modifyEntityLogic.UpdateBand(band.ID.ToString(new CultureInfo("en")), band.Name, band.Formed.ToString(new CultureInfo("en")), band.Genres, band.Members, band.Origin);
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.ViewData["editAction"] = "Edit";
                this.vm.EditedBand = band;
                return this.View("BandsIndex", this.vm);
            }
        }

        private Models.Band GetBandModel(int id)
        {
            Data.Band oneBand = this.getEntityByDefinitionLogic.GetBandById(id.ToString(new CultureInfo("en")));
            return this.mapper.Map<Data.Band, Models.Band>(oneBand);
        }
    }
}

OENIK_PROG3_2020_2_DS1D6V/FelevesFeladat.MVC/Views/Bands/BandsDetails.cshtml
@model FelevesFeladat.MVC.Models.Band

@{
    ViewData["Title"] = "BandsDetails";
}

<h2> Datasheet of one band </h2>

@Html.ActionLink("Back to the list", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.ID)</td>
        <td>@Html.DisplayFor(m => m.ID)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Origin)</td>
        <td>@Html.DisplayFor(m => m.Origin)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Members)</td>
        <td>@Html.DisplayFor(m => m.Members)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Genres)</td>
        <td>@Html.DisplayFor(m => m.Genres)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Formed)</td>
        <td>@Html.DisplayFor(m => m.Formed)</td>
    </tr>
</table>

OENIK_PROG3_2020_2_DS1D6V/FelevesFeladat.MVC/Views/Bands/BandsEdit.cshtml
@model FelevesFeladat.MVC.Models.Band

<h2>Bands edit</h2>

@using (Html.BeginForm("Edit", "Bands"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken() //Nem küldhetnek adatot kívülről, másik ürlapról a saját controllerbe

    @Html.HiddenFor(m => m.ID) //rejtett adat
    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Origin)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Origin)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Members)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Members)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Genres)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Genres)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Formed)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Formed)</div>

    <input type="submit" value="SEND"/>
}

OENIK_PROG3_2020_2_DS1D6V/FelevesFeladat.MVC/Views/Bands/BandsIndex.cshtml
@model FelevesFeladat.MVC.Models.BandListViewModel

@{
    ViewData["Title"] = "BandsIndex";
}

<h2>Bands Index</h2>

<p style="color:red">@TempData["editResult"]</p>

@await Html.PartialAsync("BandsEdit", Model.EditedBand)

@await Html.PartialAsync("BandsList", Model.Bands)

OENIK_PROG3_2020_2_DS1D6V/FelevesFeladat.MVC/Views/Bands/BandsList.cshtml
@model IEnumerable<FelevesFeladat.MVC.Models.Band>

<h2>BandsList</h2>
@if (Model.Count() == 0)
{
    <p>No data in the databse!</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Name)</th>
            <th>@Html.DisplayNameFor(m => m.First().Origin)</th>
            <th>@Html.DisplayNameFor(m => m.First().Members)</th>
            <th>@Html.DisplayNameFor(m => m.First().Genres)</th>
            <th>@Html.DisplayNameFor(m => m.First().Formed)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Modify</th>
        </tr>

        @foreach (var band in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => band.Name)</td>
                <td>@Html.DisplayFor(m => band.Origin)</td>
                <td>@Html.DisplayFor(m => band.Members)</td>
                <td>@Html.DisplayFor(m => band.Genres)</td>
                <td>@Html.DisplayFor(m => band.Formed)</td>
                <td>@Html.ActionLink("[SHOW]","Details", new { id = band.ID})</td>
                <td>@Html.ActionLink("[DELL]","Remove", new { id = band.ID})</td>
                <td>@Html.ActionLink("[EDIT]","Edit", new { id = band.ID})</td>
            </tr>
        }
    </table>
}